export default () => ({
  productList: [],
  productType: [],
  paymentType: [],
  priceType: [],
  priceTemplate: [],
  languageCode: [],
  addOn: [],
  addOnType: [],
  orderList: [],
  orderCount: 0,
  selectProduct: undefined,
  sliderPage: false,
  loadingPage: true,
  selectedKeys: '1',
})
